{
 "title": "BondPricer - Spring Boot JIT & AOT",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "CPU  Total Time used ( ms)",
   "type": "stat",
   "description": "CPU total usage in ms by containers",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"bondpricer-spring-jit\",container=\"bondpricer\"}[1h]))*1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU  Total Time used ( ms)",
   "type": "stat",
   "description": "CPU total usage in ms by containers",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"bondpricer-spring-aot\",container=\"bondpricer\"}[1h]))*1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Resource Utilization",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Memory Usage (RSS) - Lower is Better",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 18, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(container_memory_usage_bytes{namespace=\"bondpricer-spring-jit\",container=\"bondpricer\"}\n)",
     "legendFormat": " Open JDK23 - JIT"
    },
    {
     "expr": "avg(container_memory_usage_bytes{namespace=\"bondpricer-spring-aot\",container=\"bondpricer\"}\n)",
     "legendFormat": "Oracle GraalVM 23 - AOT"
    }
   ]
  },
  {
   "title": "Memory Usage Improvement",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(avg(container_memory_usage_bytes{namespace=\"bondpricer-spring-jit\",container=\"bondpricer\"})-avg(container_memory_usage_bytes{namespace=\"bondpricer-spring-aot\",container=\"bondpricer\"})\n)/ (avg(container_memory_usage_bytes{namespace=\"bondpricer-spring-jit\",container=\"bondpricer\"})) * -100"
    }
   ]
  },
  {
   "title": "Startup Times",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Start-up Time - Lower is Better",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 18, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(application_started_time_seconds{namespace=\"bondpricer-spring-jit\",service=\"bondpricer-svc\"})",
     "legendFormat": "Startup / OpenJDK"
    },
    {
     "expr": "avg(application_started_time_seconds{namespace=\"bondpricer-spring-aot\",service=\"bondpricer-svc\"})",
     "legendFormat": "Startup / Native Image"
    }
   ]
  },
  {
   "title": "Startup Time Improvement",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(application_started_time_seconds{namespace=\"bondpricer-spring-jit\"}) - sum(application_started_time_seconds{namespace=\"bondpricer-spring-aot\"})) / sum(application_started_time_seconds{namespace=\"bondpricer-spring-jit\"}) * -100"
    }
   ]
  },
  {
   "title": "Application Throughput",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Throughput - Higher is Better",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "http_server_requests_seconds_count{namespace=\"bondpricer-spring-aot\", status=\"200\", uri=\"/price/{name}/{principal}/{maturity}\"}",
     "legendFormat": "GraalVM EE (req / s)"
    },
    {
     "expr": "http_server_requests_seconds_count{namespace=\"bondpricer-spring-jit\", status=\"200\", uri=\"/price/{name}/{principal}/{maturity}\"}",
     "legendFormat": "Open JDK23 (req / s)"
    }
   ]
  }
 ]
}