FROM docker.io/oraclelinux:8-slim
EXPOSE 8080
# Copy the native executable into the containers
COPY ../target/BondPricingApp.upx /app
ENTRYPOINT ["/app"]


# Run the native executable when the container starts up 
#   podman build -f docker/Dockerfile.native.basic -t ghcr.io/nelvadas/bondpricing:2.0.0-spring-aot-graal24-x86_64 .
#   podman run -p 8080:8080 ghcr.io/nelvadas/bondpricing:2.0.0-spring-aot-graal24-x86_64