FROM docker.io/openjdk:23-oraclelinux8


# JAR file will be specified by passing in a build time argument to docker build
ARG APP_FILE=BondPricing-0.0.1-SNAPSHOT.jar

EXPOSE 8080

# opy the JAR file into the root and rename
COPY ./target/${APP_FILE} app.jar

# Run java with the jar file when the container starts up
CMD ["java","-jar","app.jar"]