FROM container-registry.oracle.com/os/oraclelinux:8

RUN yum -y install wget unzip zip findutils tar

RUN \
    # Install SDKMAN
    curl -s "https://get.sdkman.io" | bash; \
    source "$HOME/.sdkman/bin/sdkman-init.sh"; \
    # Install OpenJDK/Temurin
    sdk install java 11.0.16-tem;

EXPOSE 8080

COPY ../target/BondPricing-0.0.1-SNAPSHOT.jar app.jar
CMD ["/root/.sdkman/candidates/java/current/bin/java","-jar","app.jar"]