FROM container-registry.oracle.com/java/jdk:22.0.1-oraclelinux8

USER 1001

# JAR file will be specified by passing in a build time argument to docker build
ARG APP_FILE=MnBondPricing-0.1.jar

EXPOSE 8080

# opy the JAR file into the root and rename
COPY ./target/${APP_FILE} app.jar

# Run java with the jar file when the container starts up
CMD ["java","-jar","app.jar"]